# Generated by Django 3.0.4 on 2020-03-23 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='saved_jobs_list',
            new_name='SavedJobsList',
        ),
    ]
